spring:
  datasource:
    url: jdbc:mariadb://${AUTH_DB_SERVER:dbserver}:${AUTH_DB_PORT:30367}/authdb
    username: ${AUTH_DB_ADMIN_USER:dbadmin}
    password: ${AUTH_DB_ADMIN_PASS:adminpass}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #ddl-auto: create # uncomment this to recreate auth database
